# PersistentVolume for weaviate on local-storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: weaviate-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/weaviate
