apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
    - ssh:
        address: 192.168.86.252
        user: rl
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller+worker
      noTaints: true
    - ssh:
        address: 192.168.86.251
        user: rl
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
    - ssh:
        address: 192.168.86.250
        user: rl
        port: 1337
        keyPath: ~/.ssh/id_rsa
      role: worker
  # install Helm charts in k0s https://docs.k0sproject.io/v1.23.6+k0s.2/helm-charts/
  k0s:
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s-cluster
      spec:
        network:
          provider: calico
        extensions:
          storage:
            type: openebs_local_storage
          helm:
            repositories:
              - name: cert-manager
                url: https://charts.jetstack.io
              - name: openebs-cstor
                url: https://openebs.github.io/cstor-operators
              - name: prometheus-community
                url: https://prometheus-community.github.io/helm-charts
              - name: grafana
                url: https://grafana.github.io/helm-charts
            charts:
              - name: cert-manager
                chartname: cert-manager/cert-manager
                version: "1.8.0"
                values: |
                  installCRDs: true
                namespace: cert-manager
              - name: openebs-cstor
                chartname: openebs-cstor/cstor
                version: "3.1.0"
                values: |
                  csiNode:
                    kubeletDir: /var/lib/k0s/kubelet/
                namespace: openebs
              - name: prometheus-stack
                chartname: prometheus-community/prometheus
                version: "14.6.1"
                values: |
                  alertmanager:
                    persistentVolume:
                      enabled: false
                  server:
                    persistentVolume:
                      enabled: false
                namespace: monitoring
              - name: grafana
                chartname: grafana/grafana
                version: "6.16.2"
                values: |
                  persistence:
                    enabled: false
                namespace: monitoring
