apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
    - ssh:
        address: 192.168.86.252
        user: rl
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller+worker
      noTaints: true
    - ssh:
        address: 192.168.86.251
        user: rl
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
    - ssh:
        address: 192.168.86.250
        user: rl
        port: 1337
        keyPath: ~/.ssh/id_rsa
      role: worker
  # install Helm charts in k0s https://docs.k0sproject.io/v1.23.6+k0s.2/helm-charts/
  k0s:
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s-cluster
      spec:
        network:
          provider: calico
        extensions:
          storage:
            type: openebs_local_storage
          helm:
            repositories:
              - name: openebs-cstor
                url: https://openebs.github.io/cstor-operators
            charts:
              - name: openebs-cstor
                chartname: openebs-cstor/cstor
                version: "3.1.0"
                values: |
                  csiNode:
                    kubeletDir: /var/lib/k0s/kubelet/
                namespace: openebs
