# metallb CR ref: https://rpi4cluster.com/k3s/k3s-nw-setting/
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
spec:
  addresses:
    - 192.168.88.5-192.168.88.10
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
spec:
  ipAddressPools:
    - default-pool
